spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurant_db // поменять!!!!!!!!!!!!!!!!!!!!!!!!!!!
    username: postgres
    password: your_password // поменять!!!!!!!!!!!!!!!!!!!!!!!!!!!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
